apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- storage/storageclass-gp3.yaml
- backend/serviceaccount.yaml
- backend/configmap.yaml
- backend/migration-job.yaml
- backend/deployment.yaml
- backend/service.yaml
- backend/pdb.yaml
- frontend/deployment.yaml
- frontend/service.yaml
- frontend/pdb.yaml
- ingress.yaml

images:
- name: 074994084847.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/backend
  newName: 074994084847.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/backend
  newTag: sha-364357f
- name: 074994084847.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/frontend
  newName: 074994084847.dkr.ecr.us-east-1.amazonaws.com/devops-ia/production/frontend
  newTag: sha-a15a281

commonLabels:
  app.kubernetes.io/part-of: devops-ia
  environment: production
